Vagrant.configure("2") do |config|

    # Вебсервер
    config.vm.define "web" do |web|
        # box для web сервера
        web.vm.box = "ubuntu/bionic64"
        # Ім'я хоста
        web.vm.hostname = "web"
        # Приватна мережа для зв'язку між серверами
        web.vm.network "private_network", ip: "192.168.60.10"
        # Налаштування ресурсів
        web.vm.provider "virtualbox" do |vb|
            vb.memory = 2048 # 2 GB RAM
            vb.cpus = 1      # 1 CPU
        end
        # Перенаправлення портів для SSH та HTTP
        web.vm.network "forwarded_port", guest: 22, host: 2222
        web.vm.network "forwarded_port", guest: 80, host: 8080
        # Запуск скрипту для налаштування вебсервера
        web.vm.provision "shell", path: "web_configure.sh", privileged: false
        # Копіювання скрипту для запиту до БД
        web.vm.provision "file", source: "./db_query.sh", destination: "/home/vagrant/db_query.sh"
        # Надання прав виконання скрипту
        web.vm.provision "shell", inline: "chmod u+x /home/vagrant/db_query.sh", privileged: false
        # Вивід про готовність вебсервера
        web.vm.provision "shell", inline: "echo Web server ready"
    end

    # База даних
    config.vm.define "db" do |db|
        # box для сервера з БД
        db.vm.box = "ubuntu/focal64"
        # Ім'я хоста
        db.vm.hostname = "db"
        # Приватна мережа для зв'язку між серверами
        db.vm.network "private_network", ip: "192.168.60.20"
        # Налаштування ресурсів
        db.vm.provider "virtualbox" do |vb|
            vb.memory = 2048 # 2 GB RAM
            vb.cpus = 1      # 1 CPU
        end
        # Перенаправлення портів для SSH та БД
        db.vm.network "forwarded_port", guest: 22, host: 3333
        db.vm.network "forwarded_port", guest: 3306, host: 33060
        # Запуск скрипту для налаштування сервера бази даних
        db.vm.provision "shell", path: "db_configure.sh", privileged: false,
        # Змінні оточення для імені користувача і пароля
        env: {
            "MYSQL_USERNAME" => ENV["MYSQL_USERNAME"],
            "MYSQL_PASSWORD" => ENV["MYSQL_PASSWORD"]
        }
        # Вивід про готовність сервера бази даних
        db.vm.provision "shell", inline: "echo Database server ready"
    end

    # Моніторинговий сервер
    config.vm.define "monitoring" do |mon|
        # box для сервера з моніторингом
        mon.vm.box = "ubuntu/bionic64"
        # Ім'я хоста
        mon.vm.hostname = "mon"
        # Приватна мережа для зв'язку між серверами
        mon.vm.network "private_network", ip: "192.168.60.30"
        # Налаштування ресурсів
        mon.vm.provider "virtualbox" do |vb|
            vb.memory = 2048 # 2 GB RAM
            vb.cpus = 1      # 1 CPU
        end
        # Перенаправлення портів для SSH та Prometheus
        mon.vm.network "forwarded_port", guest: 22, host: 4444
        mon.vm.network "forwarded_port", guest: 9090, host: 9090
        # Запуск скрипту для налаштування сервера моніторингу
        mon.vm.provision "shell", path: "monitoring_configure.sh", privileged: false
        # Вивід про готовність сервера моніторингу
        mon.vm.provision "shell", inline: "echo Monitoring server ready"
    end
end
