Vagrant.configure("2") do |config|
    config.vm.provision "shell", inline: "echo Hello"

    config.vm.define "web" do |web|
        web.vm.box = "bento/ubuntu-26.04"
        web.vm.hostname = "web"
        web.vm.network "private_network", ip: "192.168.60.10"
        web.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
            vb.cpus = 1
        end
        web.vm.network "forwarded_port", guest: 22, host: 2222
        web.vm.network "forwarded_port", guest: 80, host: 8080
        # web.vm.provision "shell", path: "web_create_file.sh", privileged: false
        web.vm.provision "shell", path: "web_configure.sh", privileged: false
        web.vm.provision "shell", inline: "echo Web server ready"
    end

    config.vm.define "db" do |db|
        db.vm.box = "bento/ubuntu-26.04"
        db.vm.hostname = "db"
        db.vm.network "private_network", ip: "192.168.60.20"
        db.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
            vb.cpus = 1
        end
        db.vm.network "forwarded_port", guest: 22, host: 3333
        db.vm.network "forwarded_port", guest: 3306, host: 33060
        # db.vm.provision "shell", path: "db_create_file.sh", privileged: false
        db.vm.provision "shell", path: "db_configure.sh", privileged: false
        db.vm.provision "shell", inline: "echo Database server ready"
    end

    config.vm.define "monitoring" do |mon|
        mon.vm.box = "bento/ubuntu-26.04"
        mon.vm.hostname = "mon"
        mon.vm.network "private_network", ip: "192.168.60.30"
        mon.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
            vb.cpus = 1
        end
        mon.vm.network "forwarded_port", guest: 22, host: 4444
        mon.vm.network "forwarded_port", guest: 9090, host: 9090
        # mon.vm.provision "shell", path: "monitoring_create_file.sh", privileged: false
        mon.vm.provision "shell", path: "monitoring_configure.sh", privileged: false
        mon.vm.provision "shell", inline: "echo Monitoring server ready"
    end
end