Vagrant.configure("2") do |config|
    config.vm.provision "shell", inline: "echo Hello"

    config.vm.define "web" do |web|
        web.vm.box = "ubuntu/bionic64"
        web.vm.hostname = "web"
        web.vm.provision "shell", inline: "echo Web server ready"
        web.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
            vb.cpus = 2
        end
        web.vm.network "forwarded_port", guest: 22, host: 2222
        web.vm.provision "shell", path: "web_create_file.sh", privileged: false
    end

    config.vm.define "db" do |db|
        db.vm.box = "ubuntu/focal64"
        db.vm.hostname = "db"
        db.vm.provision "shell", inline: "echo Database server ready"
        db.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
            vb.cpus = 2
        end
        db.vm.network "forwarded_port", guest: 22, host: 3333
        db.vm.provision "shell", path: "db_create_file.sh", privileged: false
    end
end